POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Kenny Vu",
  "dateOfBirth": "1986-07-09",
  "ssn": "090786-122X",
  "gender": "male",
  "occupation": "Software developer"
}